"use strict";
const $ = id => document.getElementById(id);
let state = {};
const apiOrigin = `${location.protocol}//${location.hostname}:${location.port || 8768}`;
const automationOrigin = `${location.protocol}//${location.hostname}:8767`;
function notice(message,status="success"){const el=$("notice");el.textContent=message||"";el.className=message?status:"";}
async function api(path,options={}){const response=await fetch(`${apiOrigin}${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const data=await response.json();if(!response.ok||data.ok===false)throw new Error(data.error||"Request failed");return data;}
function selectView(){let name=location.hash.slice(1)||"system-settings";if(!$(name))name="system-settings";document.querySelectorAll("[data-view]").forEach(link=>link.toggleAttribute("aria-current",link.dataset.view===name));document.querySelectorAll(".view-card").forEach(view=>view.hidden=view.id!==name);}
function info(label,value){const card=document.createElement("div");card.className="info-card";const name=document.createElement("span");const data=document.createElement("strong");name.textContent=label;data.textContent=value??"—";card.append(name,data);return card;}
function age(epoch){if(!epoch)return"never";const seconds=Math.max(0,Math.round(Date.now()/1000-epoch));return seconds<60?`${seconds}s ago`:seconds<3600?`${Math.floor(seconds/60)}m ago`:`${Math.floor(seconds/3600)}h ago`;}
function deviceRow(device,mode){const row=document.createElement("label");row.className="device-row";const control=document.createElement("input");control.type=mode==="install"?"radio":"checkbox";control.name=mode==="install"?"install-device":"device";control.value=device.device_id;control.disabled=mode==="install"&&(!device.discovered||device.installed);control.onchange=mode==="install"?updateInstall:updateRemove;const dot=document.createElement("span");dot.className=`status-dot${device.online?" online":""}`;dot.title=device.online?"Online":"Offline";const identity=document.createElement("strong");identity.textContent=device.device_id;const badges=document.createElement("span");badges.className="badges";[[device.installed,"Installed","installed"],[device.discovered,"Discovered","discovered"]].forEach(([show,text,kind])=>{if(show){const badge=document.createElement("span");badge.className=`badge ${kind}`;badge.textContent=text;badges.append(badge);}});identity.append(badges);const detail=document.createElement("span");detail.className="device-detail";const address=device.address?`http://${device.address}:8000`:"address unknown";detail.textContent=`${address} · ${device.online?"online":"offline"} · last seen ${age(device.last_seen)}`;row.append(control,dot,identity,detail);return row;}
function render(){const settings=state.settings||{},system=state.system||{};$("system-heading").textContent=settings.title||"Nodus Automation Instrumentorum";$("system-title").value=settings.title||"";$("online-timeout").value=settings.online_timeout_seconds||150;$("auto-provision").value=settings.auto_provision===false?"no":"yes";const stationRows=[["Hostname",system.hostname],["HTTP Port",system.http_port],["MQTT Broker",system.broker],["MQTT Port",system.mqtt_port],["TLS",system.tls?"Enabled":"Disabled"],["Station",system.location],["Lat",system.latitude],["Long",system.longitude],["Alt",system.altitude],["Time Zone",system.timezone]];const runtimeRows=[["WeeWX Service",system.weewx_service],["WeeWX Config",system.weewx_config],["Database",system.database],["Dashboard",system.dashboard]];$("station-info").replaceChildren(...stationRows.map(row=>info(...row)));$("weewx-info").replaceChildren(...runtimeRows.map(row=>info(...row)));const devices=state.devices||[];const installList=$("install-device-list");installList.replaceChildren(...devices.map(device=>deviceRow(device,"install")));const removeList=$("device-list");removeList.replaceChildren(...devices.map(device=>deviceRow(device,"remove")));if(!devices.length){installList.append(info("Devices","No discovered devices"));removeList.append(info("Devices","No installed or discovered devices"));}$("automations-link").href=`${automationOrigin}/setup/#automations`;document.querySelectorAll(".dashboard").forEach(link=>{link.href=`${location.protocol}//${location.hostname}/weewx/nodus/`;});updateInstall();updateRemove();}
function updateInstall(){$("install-submit").disabled=!document.querySelector('input[name="install-device"]:checked');}
function updateRemove(){const selected=document.querySelectorAll('input[name="device"]:checked').length>0;$("remove-submit").disabled=!(selected&&$("remove-confirm").checked);}
document.addEventListener("DOMContentLoaded",async()=>{selectView();window.addEventListener("hashchange",selectView);$("remove-confirm").onchange=updateRemove;try{state=await api("/api/system");render();}catch(error){notice(error.message,"error");}$("system-form").onsubmit=async event=>{event.preventDefault();try{notice("Saving system settings…","pending");await api("/api/system",{method:"POST",body:JSON.stringify({title:$("system-title").value,online_timeout_seconds:Number($("online-timeout").value),auto_provision:$("auto-provision").value==="yes"})});state=await api("/api/system");render();notice("System settings saved.");}catch(error){notice(`System settings save failed: ${error.message}`,"error");}};$("install-form").onsubmit=async event=>{event.preventDefault();const selected=document.querySelector('input[name="install-device"]:checked');if(!selected)return;try{notice(`Installing ${selected.value}…`,"pending");const result=await api("/api/install",{method:"POST",body:JSON.stringify({device_id:selected.value})});state=await api("/api/system");render();notice(result.message);}catch(error){notice(`Device installation failed: ${error.message}`,"error");}};$("remove-form").onsubmit=async event=>{event.preventDefault();const ids=[...document.querySelectorAll('input[name="device"]:checked')].map(item=>item.value);try{notice(`Removing ${ids.join(", ")}…`,"pending");const result=await api("/api/remove",{method:"POST",body:JSON.stringify({device_ids:ids,confirm:$("remove-confirm").checked})});state=await api("/api/system");render();$("remove-confirm").checked=false;updateRemove();notice(result.message);}catch(error){notice(`Device removal failed: ${error.message}`,"error");}};});
